name: Deploy

on:
  workflow_dispatch:
    
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Build
        run: ./gradlew :composeApp:wasmJsBrowserDistribution
        
      - name: Commit and push
        run: |
          git config user.email "scto@users.noreply.github.com"
          git config user.name "scto"
          git checkout --orphan gh-pages
          git reset --hard
          git --work-tree=composeApp/build/dist/wasmJs/productionExecutable add .
          git commit -m "Upload gh-pages"
          git push origin gh-pages --force
